### ISSUE TITLE
Images used in README & wiki

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/archi-modelrepository-plugin#1]
![architeamworkvision](https://cloud.githubusercontent.com/assets/5757396/25773905/66ecf38a-3286-11e7-807a-1be70e509a32.jpg)

**Comment by Phillipus** [comment]
![image 1](https://user-images.githubusercontent.com/600504/27026905-4e29ff4e-4f57-11e7-84aa-b840aaa2a4b3.png)

**Comment by jbsarrodie** [comment]
![publishfirst](https://user-images.githubusercontent.com/5757396/44410026-d04f3f80-a563-11e8-9c1b-36e881d4749b.png)

**Comment by jbsarrodie** [comment]
![settings](https://user-images.githubusercontent.com/5757396/48571237-a6a97880-e906-11e8-8b74-5a34ccee4e8e.png)

**Comment by jbsarrodie** [comment]
![image](https://user-images.githubusercontent.com/5757396/52949993-27509880-337e-11e9-8e68-0dd8b5a87a82.png)

**Comment by jbsarrodie** [comment]
![archi-model-merge](https://github.com/archimatetool/archi-modelrepository-plugin/assets/5757396/460a73a9-20d6-4ad6-a7bb-3588101113c5)

![jarchi-delete-unused](https://github.com/archimatetool/archi-modelrepository-plugin/assets/5757396/39d0051e-902e-4369-8da1-c37bc22f1052)

**Comment by jbsarrodie** [comment]
![coarchi-extract-model](https://github.com/archimatetool/archi-modelrepository-plugin/assets/5757396/56e9ef99-6f7f-4121-ac36-002fb22afabe)
