### ISSUE TITLE
Add a way to define an HTTP proxy (in the preference window ?)

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/archi-modelrepository-plugin#10]
For the moment, the plugin works only if the user workstation has direct HTTP(S) access to git repository. In most cases this is not the case and an HTTP(S) proxy will be used. We have to allow user to define such proxy in the preferences.

Note: this is in fact also needed for Archi itself for the 'Check new version" feature...

**Comment by Phillipus** [comment]
So, is it correct that one proxy is set for the installation of Archi and that can be used by JGit and "Check new version"? If so, this preference should be part of Archi codebase.

**Comment by jbsarrodie** [comment]
Yes, only one proxy should be set for both needs. In fact this should even use proxy defined at OS level but I don t know if eclipse can do that.

**Comment by Phillipus** [comment]
Eclipse itself has a proxy preference page. I get the feeling, though, that it would probably require the whole IDE of Eclipse, the Universe, and Everything as dependencies...

**Comment by Phillipus** [comment]
I'm having a stab at this today, however I'm not behind a proxy server so can't test it. Any pointers and help would be appreciated

**Comment by jbsarrodie** [comment]
There's a software called [MockServer](http://www.mock-server.com/) that can be used as a local HTTP proxy. It is primarily used to intercept some calls and provide "mocked" answers, but if no configuration is provided then it should behaves like a real HTTP proxy (that logs, so you can be sure your browser or application use it).

Being written in java it should work for you. [Here is a doc to run it](http://www.mock-server.com/mock_server/running_mock_server.html#running_from_command_line)

**Comment by jbsarrodie** [comment]
Tested with [CCProxy](http://www.youngzsoft.net/ccproxy/) and works fine.

_We might have to add authentication through certificate, but that's not even for Sprint #2._
