### ISSUE TITLE
Create "Abort changes" action

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/archi-modelrepository-plugin#17]
This action allows the user to undo any locally made but unpublished changes. An update is provided if changes have been made by other users to the model repository. Technically the update is a "git reset".

**Comment by Phillipus** [comment]
Does this require a new toolbar icon?

**Comment by jbsarrodie** [comment]
I'd say yes.

**Comment by Phillipus** [comment]
We need to be clear what we mean by "unpublished changes".

- Commits that have not been pushed. I'd say no, because this is covered in #16 
- Local changes to the archimate.temp file and/or grafico files.

**Comment by jbsarrodie** [comment]
> Local changes to the archimate.temp file and/or grafico files.

Yes, I agree on this.

> Commits that have not been pushed. I'd say no, because this is covered in #16

Interresting remark. I would have said "yes" because IMO in #16, "Revert a commit" means keeping the commit in the history be undo changes with another commit, while here as nothing has been pushed we can just "roll back" without any trace in the commit history.

**Comment by Phillipus** [comment]
Yes, but roll back to what? All unpushed commits? The last one? The branch? If so, it would require a UI of the commit history to allow the user to be sure.

**Comment by jbsarrodie** [comment]
> Yes, but roll back to what?

My answer would be "All unpushed commits". But I agree this requires to be able to show the list to the user to avoid any issue.

So... Let's do it step by step. In this issue let's limit ourselves to undoing only local changes to the .archimate file and working tree.

**Comment by Phillipus** [comment]
Agreed. When we have a commit history view and associated actions we will have a better idea of how these actions work together.

**Comment by Phillipus** [comment]
We already have the code to roll back to "master" on local or remote. So now I'm wondering if we should define "Abort Changes" as one of these? Hmmm.....

**Comment by jbsarrodie** [comment]
> We already have the code to roll back to "master" on local or remote

Not sure to understand...

**Comment by Phillipus** [comment]
1st implementation.

- Confirm with user
- Do a "hard" reset to local master
- Clean out any addition grafico files
- Reload model

**Comment by Phillipus** [comment]
We can change this to roll back any unpushed commits now. Shall we do that?

**Comment by jbsarrodie** [comment]
I m not sure to understand the difference... Is it only a different way to do the same thing or does this lead to a different result ?

**Comment by jbsarrodie** [comment]
>The other option is to do that and roll back any unpushed commits.

Would it be done through a reset to origin/master or ? And is it now possible to show the comments associated to those local commits ?

**Comment by Phillipus** [comment]
> Would it be done through a reset to origin/master?

Yes

> And is it now possible to show the comments associated to those local commits?

Come back in an another hour.... ;-)

**Comment by jbsarrodie** [comment]
Mmmm, let me think about it. I've just played a bit with the revert actions and I might have some remarks that impact this action.
