### ISSUE TITLE
can not open git-receive-pack

### ISSUE THREAD

**Issue by itc2009** [archi-contribs/archi-modelrepository-plugin#18]
I am getting an "can not open git-receive-pack" error when trying to publish to repository
![hc_1506](https://cloud.githubusercontent.com/assets/19816866/26451988/8a28cebe-415e-11e7-840c-e03464f640dc.jpg)

**Comment by Phillipus** [comment]
This might mean an authentication error. Have you double-checked your user login details, and proxy settings if any?

**Comment by Phillipus** [comment]
Also, remember that you can only have one Archi model per git repository.

**Comment by Phillipus** [comment]
Also, remember that you can only have one Archi model per git repository.

**Comment by jbsarrodie** [comment]
And remember that the repository must have been fully created before... Which on github means at least on file (usually README.md).

**Comment by Phillipus** [comment]
I think it does exist.

https://github.com/itc2009/archimatemodels

**Comment by itc2009** [comment]
with 4.0.1 it works fine.
p.s. how can i add some existing model to the repository? or i can only start from scratch?

**Comment by Phillipus** [comment]
See issue #15

**Comment by Phillipus** [comment]
Closing.

**Comment by jbsarrodie** [comment]
FYI I had the same issue today. It was cause by some spaces added at the end of the repo url when copying it on Archi. Maybe we should trim it before passing it to jgit..

**Comment by Phillipus** [comment]
Add trim() to all dialog getters

**Comment by Phillipus** [comment]
Also, the connection is tested first before doing a git action to provide a better error message.
