### ISSUE TITLE
Add a way to "Create New Model and Share"

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/archi-modelrepository-plugin#19]
_Following Issue #15_

1. User presses button "Create New Model and Share"
2. Wizard / dialog asks for a model name, remote git URL, user name and password
3. New local repo is made ("git init")
4. New temp.archimate model is created
5. Grafico export to xml files
6. Do a first commit (perhaps get the commit message from user in dialog?)
7. Push to remote (give user choice to do this now or later?)

**Comment by Phillipus** [comment]
This is solved in #15
