### ISSUE TITLE
Add ability to visualize commits history

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/archi-modelrepository-plugin#2]
As a user I should be able to right clic on a model (in the list of remote models) and select a "Show history" action that would then open a view showing the list of changes (similar to a git log).

This should look like this:
![JGit log example](http://wiki.eclipse.org/images/e/e5/Jgit-glog.png)

JGit offers primitives to do so through org.eclipse.jgit.revplot.AbstractPlotRenderer which can be extended to add drawing capabilities either through AWT (see [example here](http://svn.wso2.org/repos/wso2/scratch/apaas/dependencies/jgit/2.3.1-wso2v2/org.eclipse.jgit.ui/src/org/eclipse/jgit/awtui/AWTPlotRenderer.java)) or SWT.

**Comment by Phillipus** [comment]
That's a nice API! This is a nice descrete little project in itself if any watcher would like to help. ;-)

**Comment by Phillipus** [comment]
@stigbd You already know how to develop with main Archi code, So just clone this plugin repo and add to Eclipse. Add the plugin feature project to the list of features in archi.product file.

**Comment by stigbd** [comment]
Thank you @Phillipus . Your last sentence solved my issues.

**Comment by Phillipus** [comment]
@stigbd Great! This Eclipse stuff is not intuitive.

**Comment by Phillipus** [comment]
First implementation is committed. More to do!

**Comment by jbsarrodie** [comment]
> First implementation is committed. More to do!

Already good!

FWIW, I've found what seems a good example inside EGit code: look at [CommitGraphTable.java](https://github.com/eclipse/egit/blob/master/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/history/CommitGraphTable.java) and [SWTPlotRenderer.java](https://github.com/eclipse/egit/blob/master/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/history/SWTPlotRenderer.java)

**Comment by Phillipus** [comment]
I found that code as well. ;-)

**Comment by Phillipus** [comment]
I've taken a look a the eGit code for the History View. There are very many dependencies on other parts of the eGit plugin and also the History framework from Eclipse SDK. The rabbit hole goes very deep.

So we have to think about whether it's worth spending more time reverse engineering this or to move on and come back to it later. Even if we use the API in JGit (AbstractPlotRenderer, PlotWalk, etc) we will need to develop something close to the eGit implementation.

**Comment by Phillipus** [comment]
Perhaps there is a simple example we could be inspired by?

**Comment by jbsarrodie** [comment]
Closing this issue as the current implementation does the job. We'll open another one later.
