### ISSUE TITLE
Add main menu actions for repository and model

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/archi-modelrepository-plugin#20]
The menu actions on the plugin view relate to the selected repository. However, some actions are more suited to the model itself when it has the focus.

**Comment by Phillipus** [comment]
I've added the menu items to the top level "Repository" menu and also to a "Repository" context menu when right click on the models tre. These relate to the selected model in the models tree.

The actions in the plugin view relate to the selected repository in the view. We need to decide which is best, and if these are needed.

**Comment by Phillipus** [comment]
The top level menu items are bound to the selected model, not what is selected in the repo view.

**Comment by Phillipus** [comment]
Added more menu items. Now we need to decide what we should keep, move, or remove.

**Comment by jbsarrodie** [comment]
> Added more menu items. Now we need to decide what we should keep, move, or remove.

Ok, I would suggest the following (to be discussed)...

First we have several actions categories depending on context:
* Actions related to the remote server
  * Add remote model
  * Create repository from selected model
* Actions related to local clones
  * Delete (Local Copy)
  * Open Model
* Actions related to the model "change workflow"
  * Refresh local copy
  * Commit changes
  * Publish changes
  * Abort unpublished changes
* Actions related to the model, outside of the "change workflow"
  * Show in history
  * Show in Model Repository

And here is how I would mix al this:

Top Level menu:
* All actions categories

Context menu on model:
* Create repository from selected model
* Delete (Local Copy)
* All actions related to the model "change workflow"
* All actions related to the model, outside of the "change workflow"

"Model Repository" view toolbar:
* Add remote model
* All actions related to local clones
* Show Repository History View

"Model Repository" view context menu on entry (ie. git repository):
* All actions related to local clones
* All actions related to the model "change workflow"
* All actions related to the model, outside of the "change workflow" (minus Show in Model Repository)

In addition, I wonder if we should not move the history from the dedicated "Repository History" view to the "Properties" view (in a new "history" tab). Would this be possible easily? if yes I'll add an issue for that.

**Comment by Phillipus** [comment]
> In addition, I wonder if we should not move the history from the dedicated "Repository History" view to the "Properties" view (in a new "history" tab). Would this be possible easily? if yes I'll add an issue for that.

I would prefer not to do this as History is its own thing. Also, there is an issue of adding History toolbar buttons to the Properties View which is a bad idea. I really prefer a dedicated History View.

**Comment by Phillipus** [comment]
Latest commit re-arranges some menu items.

**Comment by Phillipus** [comment]
We can review and change the order and/or appearance as we move along.
