### ISSUE TITLE
The "credentials" file deletion 

### ISSUE THREAD

**Issue by marbico** [archi-contribs/archi-modelrepository-plugin#22]
Checking and unchecking the "Store each repository's user name  ....", "Enable Proxy", "Requires Authentication" checkboxes and / or choice of the  "Restore Default" does not delete the "credentials" file.

**Comment by Phillipus** [comment]
That is a global setting. There is one "credentials" file for each .git folder. So if this were to happen several files would have to be found and deleted. For now, the user will have to do this manually.

Also, note the warning that says that the encryption is not strong, This is why the setting is off by default. For now it is for convenience for testers who are aware of the implications.

**Comment by marbico** [comment]
In that case, I suggest to arrange plugin configuration hierarchically:  at the first layer   server related configuration (endpoint address, credentials, proxies etc.) and then, in the context of the given server,  the second layer repository related configuration.

**Comment by marbico** [comment]
Something 

![appdata_roaming_archi4_repository servers](https://cloud.githubusercontent.com/assets/14309143/26731131/5aa97c0a-47b3-11e7-9dbc-d9b4dccd7415.jpg)

**Comment by Phillipus** [comment]
Bear in mind that it works on the basis of one model = one repository. Therefore there could be different permissions.

(Did you mean to close this issue?)

**Comment by Phillipus** [comment]
Re-opening this because I think it was closed by mistake.
