### ISSUE TITLE
"Undo last commit" should also cancel changes in working tree

### ISSUE THREAD

**Issue by Phillipus** [archi-contribs/archi-modelrepository-plugin#28]
Does this mean a "clean" of all changed files in working directory?

**Comment by jbsarrodie** [comment]
>Does this mean a "clean" of all changed files in working directory?

Yes, because what user want here is "undo the change associated to the commit", not "undo the commit action itself" (too git centric).

BTW from a UX point of view "Undo" is not perfect because this convey the idea that it is possible to "Redo"...

**Comment by Phillipus** [comment]
I've re-done this now. Note that the previous implementation did not refresh from Grafico after the undo operation.
