### ISSUE TITLE
This breaks Archi on a Mac

### ISSUE THREAD

**Issue by andy-cruk** [archi-contribs/archi-modelrepository-plugin#35]
Plugin seems to be Windows only.  See attached log file for error raised when installing plugin on a Mac running Archimate 4.0.2 and OSX 10.12.5.

Could only fix this by trashing the Application Support/Archi4 folder.

[ATT06761.log.txt](https://github.com/archi-contribs/archi-modelrepository-plugin/files/1094935/ATT06761.log.txt)

**Comment by Phillipus** [comment]
Just tried this on a fresh Archi install on Mac, works OK here.

What's interesting in that log file is this:

`java.io.FileNotFoundException: /private/var/folders/fw/x0cvty9j0xg8n72mg1v4qp1svlm1lg/T/AppTranslocation/D419BEEB-8F5F-4076-BA89-C639EEF318C2/d/Archi.app/plugins/org.archicontribs.modelrepository_0.2.1.201706152001.jar (Read-only file system)`

When installing a plugin, Archi unpacks the zip file to ~/Application Support/Archi4/.install and then copies the jar file to Archi.app/plugins. I can only suggest that one of these location is read-only on your system.

**Comment by andy-cruk** [comment]
Hi Phil

Thanks for the prompt reply.

I have done some further investigation…

1.       The file is unzipped to ~/Application Support/Archi4/.install as expected

2.       The file is not copied to /private/var/folders/….  I assume this is as it is writable only by system, not me

3.       There is also an Archi.app in ~/Applications.  Copying the jar file to the plugins folder here does not make any difference.

Should I need to have write access to /private to install this?

Any assistance welcome

Thanks

Andy

**Comment by Phillipus** [comment]
It should not be copying anything to the private/var folder at all. It only copies from ~/Application Support/Archi4/.install to Archi.app/plugins. Try moving the Archi app out of Applications.

**Comment by andy-cruk** [comment]
Deleted app and support folder.  Reinstalled. Ran from desktop.  Same problem. Log file attached
[archi.log.txt](https://github.com/archi-contribs/archi-modelrepository-plugin/files/1097339/archi.log.txt)

**Comment by Phillipus** [comment]
OK, this is something that is due to OSX 10.12.5. 

https://lapcatsoftware.com/articles/app-translocation.html

Under investigation...

**Comment by Phillipus** [comment]
I tested on OSX 10.12.5 and got the error. I then moved the Archi app to a different folder and it worked OK. So, to stop Apple's "wonderfully helpful" Translocation feature simply move the app to another folder and re-run it.

**Comment by andy-cruk** [comment]
Yes, that fixed it.  Many thanks

**Comment by Phillipus** [comment]
I added a note to the instructions

https://www.archimatetool.com/plugins
