### ISSUE TITLE
Error when publishing model first time

### ISSUE THREAD

**Issue by 1Derboy** [archi-contribs/archi-modelrepository-plugin#36]
Get error when I publish pages after commit changes. 
Error modal form over progress information: Updating references.

Error: There was an error : Remote origin did not advertise Ref for Branch Master . This ref may not exist on the remote or may be hidden by permission settings. 

Setup Archi 4.0.2 mac 
New setup on gitgub
first model to publish

**Comment by Phillipus** [comment]
Can you provide more information about how the remote is set up? What git hst is it? Did you create the repo first? Any other information would help...

**Comment by 1Derboy** [comment]
Created repository on github:
1Derboy/SolutionArchitecture
 
Add remote model to local repository from collaboration tab.
<img width="515" alt="screen shot 2017-06-27 at 12 19 34 pm" src="https://user-images.githubusercontent.com/29726941/27582940-092d7e42-5b33-11e7-8f41-526a2ff1bab2.png">

Add resource artefact to model view default view
Commit and save model with  test in notes ;Success
The click on publish changes 
then get error.

<img width="1440" alt="screen shot 2017-06-27 at 10 58 32 am" src="https://user-images.githubusercontent.com/29726941/27582817-a00b9be2-5b32-11e7-97c4-2feb12ff02dd.png">

**Comment by Phillipus** [comment]
Under investigation...

**Comment by jbsarrodie** [comment]
Your repository is currently empty. So you have to choose between two options:
* create a model in Archi and then use "Collaboration > Add local model to workspace and Publish". This will actually create the repository content on github for you.
* Initialize the repository on github (that's usually possible when creating it through some options to add a README), and then use "Collaboration > Import Remote Model to Workspace". This will load repository content and create an empty model.

So in your case you mixed both options (github not initialized but using "Import Remote Model to Workspace" which led to an unusable local copy.

**Comment by Phillipus** [comment]
I got this error when creating a new blank GitHub repo. Adding a README file is the fix. The plugin is trying to pull from an empty repo.

**Comment by 1Derboy** [comment]
Added readme. Now Works

**Comment by Phillipus** [comment]
I investigated this,

When doing a "Publish" (or a "Refresh" action), a RefNotAdvertisedException is thrown if the master ref does not exist on the remote. This should not stop the actual Publish action. So we now catch that exception and proceed with the Publish action. This means that it will push to an empty remote.
