### ISSUE TITLE
[Feature Requirement]: Add compatibility with bitbucket instead of github only.

### ISSUE THREAD

**Issue by 1Derboy** [archi-contribs/archi-modelrepository-plugin#37]
Have corporate bitbucket estate. 
Sorted CA cert registry so can connect to repo in bitbucket. 

but get error when i try to add repository.
<img width="596" alt="screen shot 2017-06-27 at 12 09 14 pm" src="https://user-images.githubusercontent.com/29726941/27582697-21b1bc36-5b32-11e7-8552-9909e03656c0.png">

**Comment by jbsarrodie** [comment]
This seems to be an issue (maybe access right) with your repository.

FWIW, This plugin has been tested with GitHub, BitBucket (in fact our main test system), GitLab and GitBlit.

**Comment by 1Derboy** [comment]
Solved.
