### ISSUE TITLE
Published changes not updating remote GIT repository

### ISSUE THREAD

**Issue by OwenT13** [archi-contribs/archi-modelrepository-plugin#39]
Hi Team, I've been testing the collaboration plugin for my organisation and am hitting an unexpected issue. I'd appreciate your advice.

I'm testing to make sure that when two people are working on the same model and publishing changes, those changes will merge and, after a model refresh, changes from both commits appear for both users.

The test case is... 
1. import the model from remote GIT (we're using stash) to both PC's
2. on each PC the users make a change to different objects
3. both commit and publish their respective changes
4. refresh the model on both PC's

I expected that once you've done this you'll see both changes reflected on both PC's. There aren't any conflicts because they are different objects.

What we're finding is the first commit / publish goes through and is reflected in the model on both PC's
The second users commit / publish is only visible on that users local model. There are no error messages, hence the second publish appears to process correctly.

Then if I delete the model from user 2 workspace and re-download the model from the repository the changes are lost. Which confirms they never wrote to the git server.

There is nothing in the log file to indicate an issue.

We're using Archi 4.0.2 (portable) and latest collaboration plugin 0.2.1.201706152001

Thanks
Owen

**Comment by OwenT13** [comment]
Just read  issue "Change History Panel Commit Message Error #38" and it is a similar issue. Only displays [local] after publish in the Change History.

**Comment by Phillipus** [comment]
It seems likely that a push action is not happening, and it is failing quietly. I've just released version 0.2.2 of the plugin. Could you try that and see if it helps?

**Comment by OwenT13** [comment]
Unfortunately that hasn't helped. I checked the installation details to confirm the plugin updated and it appears correct. I deleted the model from the workspace and re-imported, then committed and published new changes. They remain in the change history as [local].

**Comment by Phillipus** [comment]
Can you find out if a push action is being done? i.e can you check the remote repo?

**Comment by OwenT13** [comment]
running git log on the remote repo I can only see commits from one user, the other users commits aren't being pushed. Note that I'm using the same git credentials for both users on different PC's.

**Comment by OwenT13** [comment]
I have cloned the remote repo from the default Archi location to the users My Documents folder and it seems to be working. Perhaps there was some kind of permissions issue with the appdata/roaming location. The other PC had no issues with the default location. I'll continue testing and let you know if it happens again.

**Comment by OwenT13** [comment]
Now it's working I decided to try setting it back to the default location. First I physically deleted the local repo in the default location, set archi back to the default location and re-imported the model. It's working fine. I had previously tried the "delete model from workspace" and re-imported but that didn't resolve it, so am not sure why this sequence has ultimately resolved the issue.

**Comment by Phillipus** [comment]
Perhaps there was a permissions issue and it couldn't write files before pushing, but an error was not shown. I've pretty much handled all errors with an error dialog box, though.

**Comment by OwenT13** [comment]
Could be, I'll keep an eye on it as we roll out to other users and let you know if I see it happen again. Thanks for your support Phil, much appreciated.

**Comment by Phillipus** [comment]
Closing
