### ISSUE TITLE
Define key actions as seen by the user

### ISSUE THREAD

**Issue by jbsarrodie** [archi-contribs/archi-modelrepository-plugin#4]
Define workflow associated with each actions. For example: "Save" could check if remote model is accessible and if yes synchronise everything in the background (if no: save changes locally and remind user to synchronise later)

Actions identified for the moment are: ~Add/Open/Remove Bookmark, Save Model~

_(in french, will be translated soon)_
* **Importer un modèle**. Cette action guide l'utilisateur dans l'import d'un modèle contenu dans le référentiel de modèles. L'utilisateur sera guidé et devra saisir l'URL d'accès au modèle ainsi que son nom d'utilisateur et son mot de passe. Le modèle est alors importé et ouvert. Techniquement cette action créé un clone local du repository git distant contenant le modèle.
* **Ouvrir un modèle**. Cette action permet à l'utilisateur d'ouvrir un modèle précédemment importé. Une mise à jour est proposée si des modifications ont été publiées par d'autres utilisateurs sur le référentiel de modèles. Techniquement la mise à jour correspond à un "git pull".
* **Enregistrer un modèle**. Cette action sauvegarde localement les modifications sans les publier. L'utilisateur devra saisir un message décrivant ses modifications. Techniquement cela correspond à la création d'un commit local.
* **Publier un modèle**. Cette action permet à l'utilisateur de partager ses modifications avec ses collègues en les enregistrant sur le référentiel de modèles. Le cas échéant, une résolution des conflits peut être déclenchée (modalités à définir). Techniquement la publication correspond à un "git pull" suivi d'un 'git push".
* **Abandonner les modifications**. Cette action permet à l'utilisateur d'annuler les modifications faites localement mais non publiées. Une mise à jour est proposée si des modifications ont été publiées par d'autres utilisateurs sur le référentiel de modèles. Techniquement la mise à jour correspond à un "git reset".

**Comment by Phillipus** [comment]
In English:

- **Import a model**. This action guides the user in importing a model contained in the model repository. The user will be guided and will have to enter the URL to access the model as well as the username and password. The model is then imported and opened. Technically this action creates a local clone of the remote git repository containing the model.
- **Open a model**. This action allows the user to open a previously imported model. An update is provided if changes have been made by other users to the model repository. Technically the update is a "git pull".
- **Save a model**. This action locally backs up the changes without publishing them. The user will have to enter a message describing their changes. Technically this corresponds to the creation of a local commit.
- **Publish a model**. This action allows the user to share his changes with his colleagues by saving them to the (remote) model repository. If necessary, a resolution of conflicts can be triggered (details to be defined). Technically the publication corresponds to a "git pull" followed by a "git push".
- **Abort changes**. This action allows the user to undo any locally made but unpublished changes. An update is provided if changes have been made by other users to the model repository. Technically the update is a "git reset".

**Comment by jbsarrodie** [comment]
Merci ;-)

**Comment by jbsarrodie** [comment]
From [this discussion](https://github.com/archi-contribs/archi-modelrepository-plugin/issues/9)

>* Archi Save action saves the "temp.archimate" file as usual, but also triggers a Grafico export in the working tree. So there's no more need for a Save action as part of the plugin.
>* Publish action:
>   * checks if model has to be saved or if a commit is needed (uncommited changes in the working tree). If yes then ask the user if he agrees to do so (a "no" answer means cancelling the publication). If user answers "yes" then go through the commit action described below.
>   * shows a dialog to the user that explain what "publish" means and asks for a confirmation
>   * proceeds with the publication itself (is confirmed by user)
>* Commit action:
>   * shows a dialog to the user that explain what "commit" means and asks for a commit comment (which can't be empty). User can cancel of continue.
>   * saves model (which triggers a Grafico export)
>   * proceeds with the commit.

**Comment by Phillipus** [comment]
What's the Refresh story?

I have:

1. Offer to save the model if dirty
2. If there are local changes offer to Commit (perhaps?)
3. Pull from Remote
4. Handle Merge conflicts
5. Reload temp file from Grafico files

Should we offer to do a commit or not? Or just do a Grafico export?

**Comment by jbsarrodie** [comment]
Done in a local document (in french). I now have to write it on a wiki page (in english)...

**Comment by jbsarrodie** [comment]
Done in a [new wiki page](https://github.com/archi-contribs/archi-modelrepository-plugin/wiki/Actions).
