### ISSUE TITLE
[Feature] Add possibility to have more than one model in a repo

### ISSUE THREAD

**Issue by poum** [archi-contribs/archi-modelrepository-plugin#49]
The plugin works great (tested with a corporate gitlab with a self signed certificate after keytool import).
But my use case would be having a single repo with several models in their own folder.

Would this be doable ? Maybe adding a "path" parameter (empty by default) allowing choosing a subdirectory in the repo  ....

Anyway, many thanks for the plugin

**Comment by jbsarrodie** [comment]
Hi,

Happy to hear it works and provide value.

What you describe is a solution to a problem, but what is your problem behind ? What's your real use-case ?

Regards

**Comment by poum** [comment]
My issue is I can't put severals distinct models in the same repo. I work on lot of systems and I can't have a repo for each, so I wish to have a single repo to store all of them, one per folder ....
Or maybe have I missed something ...

**Comment by jbsarrodie** [comment]
>I work on lot of systems and I can't have a repo for each

It depends on what you call "systems", but the general idea behind ArchiMate is to have a global model of your enterprise, thus all your "systems". The added value is to be able to link all tose systems together and to do global impact analysis when needed.

**Comment by poum** [comment]
Obviously you're right, I will work this way (and still learning archimate ,proven here I have a lot to learn still)
Thanks again

**Comment by jbsarrodie** [comment]
>Thanks again

You're welcome !
