### ISSUE TITLE
Moving between github repositories....

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/archi-modelrepository-plugin#53]
I currently point my model to a github repository, but need to change repositories.

I was hoping I could save my model locally, and then move it to a different repository, however, I cannot figure out how to point to the new one, instead of publishing to the old one.

Is there something I need to reset to be able to do that?

**Comment by GeoffMurray** [comment]
Oh - I think I found it. After I do the Save As, I have to close the old model still, and open the new one. Then I get the correct prompts.

**Comment by Phillipus** [comment]
Changing the target online repo is something that could be added as a feature, perhaps? We could re-open this...
